### ISSUE TITLE
Access 'live' console output

### ISSUE THREAD

**Issue by t-knapp** [gsliepen/tinc#113]
I am trying to access the output of `tinc join INVITATION` and `tinc -n NETWORK start -D -d3` via an AutoIT Script on Windows 7.

I neither can read 'live' output generated by tinc join nor tinc start. But reading tinc --version or tinc --help works. 

I also tried to access the console output via Java, but the output is always empty, while tinc is running.

Do you use different techniques to write to console in tinc --version and tinc start?

**Comment by gsliepen** [comment]
On Sun, May 01, 2016 at 07:17:44AM -0700, Tobias Knapp wrote:

> I am trying to access the output of `tinc join INVITATION` and `tinc -n NETWORK start -D -d3` via an AutoIT Script on Windows 7.
> 
> I neither can read 'live' output generated by tinc join nor tinc start. But reading tinc --version or tinc --help works. 
> 
> I also tried to access the console output via Java, but the output is always empty, while tinc is running.
> 
> Do you use different techniques to write to console in tinc --version and tinc start?

Note that there are two outputs; stdout and stderr. You should handle
both in your AutoIT Script. Tinc mostly writes to stderr, unless asked
specifically for some output (like --version, or the "tinc get" or "tinc
invite" commands).

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>

**Comment by t-knapp** [comment]
Thank you. Reading stderr works.
