### ISSUE TITLE
BPF Supports

### ISSUE THREAD

**Issue by zzj1213** [gsliepen/tinc#114]
[eBPF (Extended Berkeley Packet Filters)](https://lkml.org/lkml/2015/4/14/232) is a new feature that was first added to Linux 3.15.  Will Tinc 1.x supports it ?  

> "One of the more interesting features in this cycle is the ability 
>    to attach eBPF programs (user-defined, sandboxed bytecode executed 
>    by the kernel) to kprobes. This allows user-defined instrumentation 
>    on a live kernel image that can never crash, hang or interfere with 
>    the kernel negatively. (Right now it's limited to root-only, but in
>    the future we might allow unprivileged use as well.)"

From: https://lkml.org/lkml/2015/4/14/232

**Comment by gsliepen** [comment]
On Sat, May 07, 2016 at 08:01:11PM -0700, John wrote:

> [eBPF (Extended Berkeley Packet Filters)](https://lkml.org/lkml/2015/4/14/232) is a new feature that was first added to Linux 3.15.  Will Tinc 1.x supports it ?  

What use case do you have in mind for eBPF support in tinc?

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>

**Comment by ccaapton** [comment]
This can help implementing udp inbound packets whiltelist(only hosts with alive meta-connections) to prevent DOS attack?

**Comment by gsliepen** [comment]
This can be done with regular firewall rules as well. In fact, one can block UDP by default in tinc-up:

    iptables -A INPUT -p udp --dport 655 -j DENY

And then add exceptions in the host-up script:

    iptables -I INPUT 1 -p udp --dport 655 -s $REMOTEADDRESS -j ACCEPT

And remove them in host-down:

    iptables -D INPUT -p udp --dport 655 -s $REMOTEADDRESS -j ACCEPT

Of course, putting this into its own chain is better.

**Comment by gsliepen** [comment]
I'm closing this bug, as I don't think BPF support is that useful. Even if it is, it can probably be configured in some way outside of tinc.
