### ISSUE TITLE
Feature request: Configurable deadline for invites

### ISSUE THREAD

**Issue by alfreddatakillen** [gsliepen/tinc#129]
Currently, invites are valid for 1 week, which is hard coded (version 1.1pre14). I would like them to be valid for just a couple of seconds, since I'm scripting the invite/join process. It would be great to be able to configure the TTL!

**Comment by gsliepen** [comment]
On Mon, Oct 24, 2016 at 06:32:38PM -0700, Alfred Godoy wrote:

> Currently, invites are valid for 1 week, which is hard coded (version 1.1pre14). I would like them to be valid for just a couple of seconds, since I'm scripting the invite/join process. It would be great to be able to configure the TTL!

Yes, that's something I will add. In the mean time, a workaround is to
just delete the invitation file yourself from your scripts. For example,
if you have an invitation-created script, add this:

(sleep 5; rm -f "$INVITIATION_FILE") &

This will remove the invitation after 5 seconds.

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>

**Comment by gsliepen** [comment]
This was added in commit cd854fa86a9dc177dcaa56fa774afb127b29651a. Use the `InvitationExpire` configuration variable in `tinc.conf` to set the timeout for invitations.
