### ISSUE TITLE
undocumented config option: MaxTimeout

### ISSUE THREAD

**Issue by bof** [gsliepen/tinc#140]
Playing with tinc and missing (in documentation) a way to modify the 900 second maximum timeout for reconnect attempts, a look at the source revealed that there _is_ a MaxTimeout setting to that effect, and that it even works :)

Shouldn't it be added to the documentation?

**Comment by gsliepen** [comment]
On Sun, Jan 08, 2017 at 01:27:38AM -0800, Patrick Schaaf wrote:

> Playing with tinc and missing (in documentation) a way to modify the 900 second maximum timeout for reconnect attempts, a look at the source revealed that there _is_ a MaxTimeout setting to that effect, and that it even works :)
> 
> Shouldn't it be added to the documentation?

Hm, you're right, it's missing in the info manual of tinc 1.1. It is in
the manual of tinc 1.0.x, and it's in the manpages of all versions.
Strange! But I'll add it back :)

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>

**Comment by bof** [comment]
Thanks for the quick response!
