### ISSUE TITLE
addtap.bat and deltapall.bat should change to the directory they are located in when ran

### ISSUE THREAD

**Issue by andOlga** [gsliepen/tinc#144]
These files require to be ran with admin rights, otherwise driver installation will fail. The most intuitive way to do this, is to right-click the file and choose "Run as administrator". However, that means the working directory is set incorrectly to C:\Windows\System32 instead of the location of the .bat file (blame Microsoft for that). Simply adding `cd /d "%~dp0"` to the top of both scripts should solve the issue. I'd commit the change myself but I can't seem to find these two files in the source tree.

**Comment by gsliepen** [comment]
These files are not in the source tree on purpose. But thanks for the tip, I'll add the line to the scripts for the next release!
