### ISSUE TITLE
Feature request: FIPS mode

### ISSUE THREAD

**Issue by superit23** [gsliepen/tinc#149]
I've read from the mailing list that tinc was not FIPS compatible due to the use of non-compliant algorithms from a non-validated library (https://www.tinc-vpn.org/pipermail/tinc/2016-July/004610.html). However, since then, tinc has switched over to using FIPS compliant algorithms (AES-256, SHA-256, RSA) from a library with a FIPS validated module (OpenSSL). If I'm correct, then the only thing left to do to gain compliance is a call out to `FIPS_mode_set()`. Would it be possible to add a flag like `--fips-mode` that runs this check in the `main` function?

**Comment by breisig** [comment]
Adding a flag or run-time option to enable FIPS mode would be greatly needed. [for tinc 1.1].

**Comment by breisig** [comment]
Could we get FIPS mode merged into the 1.1 branch? This feature is really important.

**Comment by gsliepen** [comment]
No. If you want to be FIPS-compliant, don't use tinc.Tinc implements its own cryptographic protocols on top of the basic building blocks provided by OpenSSL (for the legacy protocol), or provided by public domain code written by Daniel J. Bernstein for the new protocol. The latter is certainly not FIPS-compliant, and while you can flick a switch to make OpenSSL itself think it is FIPS-compliant, that doesn't mean tinc as a whole is FIPS-compliant. I do not want to pretend tinc is FIPS compliant, and I don't want to go through the effort to certify that it is FIPS-compliant.
