### ISSUE TITLE
SIGHUP in 1.0

### ISSUE THREAD

**Issue by stronny** [gsliepen/tinc#155]
Hi! Looking at changelog I wan't able to find an answer whether the bug has been fixed, and our testing suggests it wasn't. We have to restart daemons now and it leads to connectivity issues, so it would be really neat to reload the hostfiles instead.

https://www.tinc-vpn.org/pipermail/tinc/2015-October/004264.html

**Comment by stronny** [comment]
Whoo, thanks a largest amount possible! However please clarify one other thing. If we modify tincd's own hostfile with a new subnet, will tincd apply this change or will reload make use of it or should we still restart tincd? I mean other tincds will expect this tincd to announce its new subnet, so it has to somehow learn that there is in fact a new subnet behind. Hope my explanation makes sense.

Thanks again!

**Comment by gsliepen** [comment]
On Fri, Oct 06, 2017 at 09:02:51PM +0000, undead robot wrote:

> Whoo, thanks a largest amount possible! However please clarify one other thing. If we modify tincd's own hostfile with a new subnet, will tincd apply this change or will reload make use of it or should we still restart tincd? I mean other tincds will expect this tincd to announce its new subnet, so it has to somehow learn that there is in fact a new subnet behind. Hope my explanation makes sense.

You have to restart tincd on a node if you change its Subnets. As the
manual explains, SIGHUP will only react to changes in ConnectTo
statements, and will delete connections to hosts whose host config files
are removed. I'll probably add support for reloading Subnets in tinc 1.1
in the future.

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>

**Comment by stronny** [comment]
So if we use StrictSubnets there's no way around restarting every tincd in the network, is there?

**Comment by gsliepen** [comment]
On Sat, Oct 07, 2017 at 03:10:04PM +0000, undead robot wrote:

> So if we use StrictSubnets there's no way around restarting every tincd in the network, is there?

Ah, with StrictSubnets it is different. There it is actually rereading
all Subnets on SIGHUP. I should document that :)

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>

**Comment by stronny** [comment]
That's great news, Guus. Thanks!
