### ISSUE TITLE
[digression] tweak the rpm spec so that tinc.rpm owns /etc/tinc

### ISSUE THREAD

**Issue by aflyhorse** [gsliepen/tinc#159]
e.g. add ```%dir %{_sysconfdir}/tinc``` into ```%file``` section.
BTW, would you mind drop the rpm spec and debian directory into tarball (might into distro dir) as well?

**Comment by gsliepen** [comment]
Sorry, but I won't include distribution-specific files into the source code distribution of tinc. It is up to the maintainers of distributions to manage those files themselves. If you find issues in packaged versions of tinc, please contact the respective package maintainers.
