### ISSUE TITLE
tinc@.service hardcodes /usr/sbin/tincd path

### ISSUE THREAD

**Issue by pjv** [gsliepen/tinc#160]
I don't do a lot of compiling from source, so forgive me if this is just ignorance, but I recently compiled 1.1pre15 from source on Ubuntu 17.10. I wanted the binaries to be located in standard system (not /usr) directories, and I wanted to manage the service with systemd so the configuration was done like this:

`./configure --prefix= --with-systemd`

then `make`
then `sudo make install`

When I then configured a network and tried to bring the tinc service up using

`systemctl enable tinc@<netname>`

the service didn't come up and the error log told me that `/usr/sbin/tincd` was not found.

To make it work, I had to edit the `tinc@.service` file that was installed in `/lib/systemd/system/tinc@.service` and change the two instances of `/usr/sbin/tincd` to `/sbin/tincd`. 

After that, everything worked as expected.

Maybe I don't understand how `./configure` is supposed to work, but when I ran it with `--prefix=` isn't that what made the install directory for tincd be `/sbin/` and shouldn't that have also modified the `tinc@.service` file so that it pointed to the correct path?

Or do I have this all wrong?

**Comment by gsliepen** [comment]
You are right, it's currently hardcoded and it shouldn't be.
