### ISSUE TITLE
Allow tinc generate-ed25519-keys to be non-interactive

### ISSUE THREAD

**Issue by nh2** [gsliepen/tinc#162]
I deal with setting up automated deployments a lot, and one current pain point is that `tinc generate-ed25519-keys` really wants to be interactive.

It would be great if it could learn a flag so that it can be given the location where to generate its keys, like OpenSSL supports.

**Comment by nh2** [comment]
For others with the same problem, my current workaround is using `expect`:

```
expect -c 'spawn "tinc" "generate-ed25519-keys"; send "ed25519_key.priv\r"; send "ed25519_key.pub\r"; expect eof'
```

**Comment by gsliepen** [comment]
You can use the --batch option in combination with --config:

    tinc --batch --config /tmp/ generate-ed25519-keys

This will create `ed25519_key.pub` and `.priv` in `/tmp/`.

**Comment by nh2** [comment]
Fantastic, that works, and also thanks for 50afa82a8f14ead7d4d3eafd2a1347b3bb9a2879.
