### ISSUE TITLE
tincd 1.0.31 Segmentation fault

### ISSUE THREAD

**Issue by kolorafa** [gsliepen/tinc#191]
Where can I find clues about what's going wrong.
Thanks

OS: Debian 9

# tincd -n vpn -D -d
tincd 1.0.31 starting, debug level 1
Segmentation fault

# strace tincd -n vpn -D -d
(...)
open("/etc/tinc/vpn/tinc.conf", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=93, ...}) = 0
read(3, "Name = usa02\nMode = switch\nConne"..., 4096) = 93
read(3, "", 4096)                       = 0
close(3)                                = 0
open("/etc/tinc/vpn/conf.d", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
rt_sigaction(SIGHUP, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGILL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGTRAP, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGABRT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGBUS, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGFPE, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGKILL, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = -1 EINVAL (Invalid argument)
rt_sigaction(SIGUSR1, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGSEGV, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGUSR2, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGALRM, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGSTKFLT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGCHLD, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGCONT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGSTOP, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = -1 EINVAL (Invalid argument)
rt_sigaction(SIGTSTP, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGTTIN, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGTTOU, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGURG, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGXCPU, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGXFSZ, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGVTALRM, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGPROF, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGWINCH, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGIO, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGPWR, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGSYS, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_2, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_3, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_4, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_5, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_6, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_7, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_8, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_9, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_10, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_11, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_12, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_13, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_14, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_15, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_16, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_17, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_18, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_19, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_20, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_21, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_22, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_23, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_24, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_25, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_26, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_27, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_28, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_29, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_30, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_31, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGRT_32, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGHUP, {sa_handler=0x5615102611b0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGTERM, {sa_handler=0x561510261250, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGQUIT, {sa_handler=0x561510261210, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGSEGV, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGBUS, {sa_handler=0x561510261320, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGILL, {sa_handler=0x561510261320, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=0x561510261570, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGINT, {sa_handler=0x5615102614d0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGUSR1, {sa_handler=0x561510261310, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGUSR2, {sa_handler=0x5615102612f0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGCHLD, {sa_handler=0x561510261570, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGALRM, {sa_handler=0x561510261180, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGWINCH, {sa_handler=0x561510261170, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
rt_sigaction(SIGABRT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fbe171df060}, NULL, 8) = 0
open("/var/run/tinc.vpn.pid", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=6, ...}) = 0
read(3, "10005\n", 4096)                = 6
close(3)                                = 0
getpid()                                = 10008
kill(10005, SIG_0)                      = -1 ESRCH (No such process)
open("/var/run/tinc.vpn.pid", O_RDWR|O_CREAT, 0644) = 3
fcntl(3, F_GETFL)                       = 0x8002 (flags O_RDWR|O_LARGEFILE)
flock(3, LOCK_EX|LOCK_NB)               = 0
getpid()                                = 10008
fstat(3, {st_mode=S_IFREG|0644, st_size=6, ...}) = 0
write(3, "10008\n", 6)                  = 6
flock(3, LOCK_UN)                       = 0
close(3)                                = 0
getpid()                                = 10008
write(2, "tincd 1.0.31 starting, debug lev"..., 36tincd 1.0.31 starting, debug level 1) = 36
write(2, "\n", 1
)                       = 1
open("/etc/tinc/vpn/hosts/usa02", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0600, st_size=857, ...}) = 0
read(3, "Address = 54.39.56.183\nSubnet = "..., 4096) = 857
read(3, "", 4096)                       = 0
close(3)                                = 0
open("/etc/tinc/vpn/rsa_key.priv", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0600, st_size=3243, ...}) = 0
fstat(3, {st_mode=S_IFREG|0600, st_size=3243, ...}) = 0
read(3, "-----BEGIN RSA PRIVATE KEY-----\n"..., 4096) = 3243
close(3)                                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x8} ---
+++ killed by SIGSEGV +++
Segmentation fault
root@usa02:/etc/tinc/vpn#

**Comment by ccaapton** [comment]
Is it this one https://github.com/gsliepen/tinc/issues/142 ?

**Comment by kolorafa** [comment]
Yes, i think so, I remember i did try changing Cipher, but I probably did have Cipher=none in multiple places. Testing it now with correctly set cipher and everything works fine :)
Thanks for reply.
