### ISSUE TITLE
Tinc VPN - can not access local LAN subnet

### ISSUE THREAD

**Issue by norge169** [gsliepen/tinc#192]
Hi,

I want to have the same functionality described as below, but do not know how to achieve it, any tips?
[https://www.questarter.com/q/tinc-vpn-can-not-access-local-lan-subnet-1_909795.html](url)

**Comment by codingcool21** [comment]
Based on the article above, you have to setup NAT forwarding rules in order for the VPS to access the local network.

First ensure that in the host file for the RPi you have defined the local LAN subnet.
`Subnet = 10.0.0.0/24`

Ensure that this host file is up to date in the VPS and in the RPi.

Then...
**RPi**
You need to add commands to the tinc-up script:

tinc-up:

`#!/bin/bash`
`ifconfig $INTERFACE 10.0.10.2 net mask 255.255.255.0`
`iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE`
`iptables -A FORWARD -i tun0 -j ACCEPT`

tinc-down:

`#!/bin/bash`
`iptables -D FORWARD -i tun0 -j ACCEPT`
`iptables -D POSTROUTING -t nat -o eth0 -j MASQUERADE`
`ifconfig $INTERFACE down`

The above will work assuming that
- eth0 is your local LAN interface on the RPi
- tun0 is the tinc VPN interface

**VPS**
You need to add a route explicitly for the local subnet...

tinc-up:

`#!/bin/bash`
`ifconfig $INTERFACE 10.0.10.1 netmask 255.255.255.0`
`ip route add 10.0.0.0/24 dev $INTERFACE`

tinc-down:

`#!/bin/bash
`ip route del 10.0.0.0/24 dev $INTERFACE`
`ifconfig $INTERFACE down`

Once this setup is done, restart tincd on both the VPS and RPi and verify if you can access the local subnet from VPS.

**Comment by norge169** [comment]
Can you give the configuration commands on windows?

**Comment by codingcool21** [comment]
Sorry! I'm not sure how to configure on Windows. Some Google searches show me that it is very hard to implement.

But, you could play around with `netsh` tool in Command Prompt.

Good luck.

**Comment by JustBru00** [comment]
> Can you give the configuration commands for windows? I run tinc on windows.

You will probably have to configure windows manually. 
This example still works even on Windows 10: http://tinc-vpn.org/examples/windows-install/
