### ISSUE TITLE
--force parameter does not affect join command

### ISSUE THREAD

**Issue by Teteros** [gsliepen/tinc#196]
From the man page:

> --force             Force some commands to work despite warnings.
>      -b, --batch  Don't ask for anything (non-interactive mode).

$ tinc --batch --force --config=.  join 127.0.0.1/hashkey
```
Connected to 127.0.0.1 port 655...
Ignoring unsafe variable 'AddressFamily' in invitation.
Ignoring unsafe variable 'UPnP' in invitation.
......+++ p
.........................................+++ q
A tinc-up script was generated, but has been left disabled.
Configuration stored in: .
Invitation successfully accepted.
```
Without `--batch` the joining user is prompted whether they want to accept the given `tinc-up` script, refuse, or edit it.

With `--batch` the prompt is ignored, and the default action is to refuse.

"unsafe variables"? are always ignored.

It would be useful for the non-interactive mode if `--force` could accept the tinc-up prompt and possibly the "unsafe variables". As it is, the invitation script isn't very useful to automate turning on some features like UPnP and IPv4 handling only.

Below is the basic `invitation-created` script I used, slightly modified from the tinc 1.1 manual:

```
#!/bin/sh

cat >$INVITATION_FILE <<EOF
Name = $NODE
Ifconfig = dhcp
Route = 10.10.10.0/24 10.10.10.10
AddressFamily = ipv4
ConnectTo = $NAME
Mode = switch
UPnP = yes
#---------------------------------#
EOF

tinc export >>$INVITATION_FILE
```

**Comment by fangfufu** [comment]
I feel this is outside user's expectation. I am classifying this as a bug. Does this affect 1.1pre17?
