### ISSUE TITLE
Do you support port forwarding?

### ISSUE THREAD

**Issue by Bunnyk001** [gsliepen/tinc#204]
Do you support port forwarding?   Nat Port Forwarding       TCP/UDP

**Comment by igel-kun** [comment]
I am running a setup with an RPI behind a NAT with port forwarding and a laptop that I also take to work. It's running flawlessly (usually) both at home and at work. Long story short, the answer is "yes".

**Comment by fangfufu** [comment]
Tinc by default listens to TCP port 655 and UDP port 655, please refer to:
https://www.tinc-vpn.org/documentation/Main-configuration-variables.html#Main-configuration-variables

No, it does not automatically open the ports for you on your router. You need to refer to your router's user manual to configure that.

**Comment by gsliepen** [comment]
Tinc 1.1 has support for the UPnP protocol, see: https://www.tinc-vpn.org/documentation-1.1/Main-configuration-variables.html#index-UPnP
