### ISSUE TITLE
Receiving packet failed: Invalid argument = 41

### ISSUE THREAD

**Issue by lancethepants** [gsliepen/tinc#207]
I've been compiling tinc for various home routers. I periodically update my toolchain, and somewhere on the way unclear to me I come upon this below error for my mipsel based router.  My nearly identical arm toolchain (except building against 2.6.36.4 kernel)  works alright though.

Receiving packet failed: Invalid argument) = 41

Here is a strace of the issue (hopefully sufficiently scrubbed)
https://pastebin.com/cpMFt3sx

Linux Kernel: 2.6.22.19
GCC 8.2
binutils 2.31.1
uclibc-ng 1.0.30

cat /proc/cpuinfo
system type             : Broadcom BCM5357 chip rev 1 pkg 8
processor               : 0
cpu model               : MIPS 74K V4.9
BogoMIPS                : 149.91
cpu MHz                 : 300
wait instruction        : no
microsecond timers      : yes
tlb_entries             : 64
extra interrupt vector  : no
hardware watchpoint     : yes
ASEs implemented        : mips16 dsp
shadow register sets    : 1
VCED exceptions         : not available
VCEI exceptions         : not available
unaligned_instructions  : 56

**Comment by gsliepen** [comment]
On Fri, Sep 21, 2018 at 09:59:51AM -0700, Lance Fredrickson wrote:

> I've been compiling tinc for various home routers. I periodically update my toolchain, and somewhere on the way unclear to me I come upon this below error for my mipsel based router.  My nearly identical arm toolchain (except building against 2.6.36.4 kernel)  works alright though.

Aha, it is failing in the recvmmsg() call, and according to its manpage,
this function was only added in Linux 2.6.33. So if you downgraded to
2.6.22.19, that would explain why it stopped working. Tinc has an
autoconf check for recvmmsg(), but that only checks if libc knows about
the function. And apparently your libc doesn't emulate the function if
it's not present in the kernel.

After running ./configure, you can edit config.h and remove or comment
out the line that says #define HAVE_RECVMMSG 1, and then recompile tinc
to make it avoid using that function.

-- 
Met vriendelijke groet / with kind regards,
     Guus Sliepen <guus@tinc-vpn.org>

**Comment by lancethepants** [comment]
Thanks so much for the insight! Looks like uclibc-ng implemented recvmmsg/sendmmsg late last year with this commit, which is probably more recent than the last time I compiled tinc.

https://cgit.uclibc-ng.org/cgi/cgit/uclibc-ng.git/commit/?id=6e15fafa20066634a58d412b259b117a47ca46d1

uclibc-ng claims compatibility as far back as 2.6.x, so this looks like a libc issue where recvmmsg/sendmmsg should only be included with a sufficiently new Linux kernel.
Using your suggestion it compiles and runs as it should.
thanks!
