### ISSUE TITLE
Is Tinc 2.0 still a go?

### ISSUE THREAD

**Issue by mark-stopka** [gsliepen/tinc#225]
I see a great value in Tinc 2.0, but it seems the project has been stall for years, what is the biggest roadblock?

**Comment by Scafir** [comment]
I second this, the improvement in features (tinc invite for example) makes a new release very desirable. If donations would help, I'd be willing to contribute

**Comment by mark-stopka** [comment]
I would be willing to financially contribute as well!

**Comment by bytegetter** [comment]
What about a crowdfunding?

**Comment by mark-stopka** [comment]
@bytegetter, @Scafir we will be building `p2p` VPN solution of our own eventually, we started with some low-level networking in Rust [recently here](https://github.com/2nd-Layer/rust-cardano-ouroboros-network), once we (@pavlix) get that out of the way, we will evaluate [PolderCast](https://github.com/primetype/poldercast) and the improvements that @NicolasDP is making to both PolderCast and [new cryptography he is working on](https://github.com/primetype/keynesis).

**Comment by bytegetter** [comment]
@mark-stopka: For Linux, MAC, Windows and OpenWRT?

**Comment by mark-stopka** [comment]
@bytegetter Linux (which also includes OpenWRT) would be the primary platforms, as this will be part of an SD-WAN solution, I suppose no issues on the side of Mac OS X also, but I am not sure how / if we are going to focus on Windows...

**Comment by hvisage** [comment]
I notice that @gsliepen haven't responded ;(
Perhaps time for somebody to step up and take over development?

I do like tinc for several reasons where wireguard/openvpn just doesn't do it for me, but zerotier might be the direction to go? ;(

**Comment by wenerme** [comment]
Tried zerotier, never want to use again, tinc is unique, the alternative maybe nebula or mesh enabled wireguard like https://github.com/wiretrustee/wiretrustee, but none of them provide L2 network.

**Comment by fangfufu** [comment]
Please refer to this email:
https://www.tinc-vpn.org/pipermail/tinc/2021-June/005570.html

We are still working towards releasing Tinc 1.1.
