### ISSUE TITLE
[1.1] Segmentation fault in `send_udp_probe_packet`

### ISSUE THREAD

**Issue by furkanmustafa** [gsliepen/tinc#227]
[`send_udp_probe_packet`](https://github.com/gsliepen/tinc/blob/1.1/src/net_packet.c#L1086) in `src/net_packet.c` does not check for boundary when calling memset.

I think there are other causes for this problem to occur, but this is the last step before segmentation fault.

I have added one line log and saw the problem there;

```diff
 static void send_udp_probe_packet(node_t *n, int len) {
+	fprintf(stderr, "send_udp_probe_packet(node_t, %d) but MAXSIZE is %lu\n", len, MAXSIZE);
```

And the last output before segfault was;

```
send_udp_probe_packet(node_t, 66283) but MAXSIZE is 1673
```

I will now investigate further after adding a memory protection there.

**Comment by furkanmustafa** [comment]
With the memory protection, it at least doesn't crash now, and connectivity is okay.

That meaningless value (66283) send to the function above is a bit worrying.. It felt like there probe sizes are extreme, like sometimes 18 bytes, sometimes 1000~ish, sometimes 60k+ like this.

I have mixed CPU architectures in my setup, but not extreme; only amd64, arm64. Can that be the cause?

I have this log continously repeating for my arm64 boards (Rock64)

```
ERROR! send_udp_probe_packet(node_t, 66047) but MAXSIZE is 1673
Packet is 819 seqs in the future, dropped (1) from rock1 (10.74.1.64 port 1259)
Packet is 820 seqs in the future, dropped (2) from rock1 (10.74.1.64 port 1259)
Packet is 821 seqs in the future, dropped (3) from rock1 (10.74.1.64 port 1259)
Packet is 822 seqs in the future, dropped (4) from rock1 (10.74.1.64 port 1259)
Lost 823 packets from rock1 (10.74.1.64 port 1259)
Got REQ_KEY from rock2 while we already started a SPTPS session!
ERROR! send_udp_probe_packet(node_t, 66047) but MAXSIZE is 1673
Got REQ_KEY from rock1 while we already started a SPTPS session!
Packet is 820 seqs in the future, dropped (1) from rock2 (10.74.1.65 port 1259)
Packet is 821 seqs in the future, dropped (2) from rock2 (10.74.1.65 port 1259)
Packet is 822 seqs in the future, dropped (3) from rock2 (10.74.1.65 port 1259)
Packet is 823 seqs in the future, dropped (4) from rock2 (10.74.1.65 port 1259)
Lost 824 packets from rock2 (10.74.1.65 port 1259)
```

**Comment by gsliepen** [comment]
It should not matter that you have mixed CPU architectures. However, it points to some programming error elsewhere, the length passed into `send_udp_probe_packed()` should be derived from the maximum MTU, which should never be more than `MAXSIZE`. I wonder if this might also trigger bugs in other functions.

It seems you can easily reproduce this issue?

**Comment by furkanmustafa** [comment]
> It seems you can easily reproduce this issue?

Yes, I believe so. If you'd like me to inject some extra logs and reproduce the issue, I can do that.

I was using `switch` mode. The logs have stopped after I switch to `router` mode and made a few adjustments, like restricting listen addresses. Also the logs about wrong sequences and lost packets are also stopped.

And in my setup I have several tinc networks, and my gate nodes has several tinc networks enabled at once on them. One of the problems I have realized that, naturally tinc is listening on all interfaces, and those include any other vpn interfaces & tinc interfaces too. It might have caused loops..

Looks like this is the most suspectible place for such error => https://github.com/gsliepen/tinc/blob/1.1/src/net_packet.c#L1337

**Comment by splitice** [comment]
PR #273 should fix this

**Comment by fangfufu** [comment]
Fixed via https://github.com/gsliepen/tinc/pull/273#issuecomment-871753419
