### ISSUE TITLE
Segfault with x86_64-w64-mingw-w64

### ISSUE THREAD

**Issue by wolfy1339** [gsliepen/tinc#230]
I have determined via `git bisect` that d6b45d005530496e48325a6174ecdd889a17bfc1 is the commit that introduces the segfault.
The produced binary runs for a couple seconds then it segfaults
`1.1-pre17` compiles and runs fine

**Comment by wolfy1339** [comment]
`x86_64-w64-mingw32.static-gcc (GCC) 5.5.0` provided by [mxe](https://mxe.cc/)

**Comment by wolfy1339** [comment]
I just compiled a newer GCC just to test and 9.2.0 is the same

**Comment by arsh0r** [comment]
after [these](https://github.com/arsh0r/tinc/commit/b8bf6cc7b8da33a5d74a8eba4ab93f55a310184a) changes it compiles and runs for me.

**Comment by fangfufu** [comment]
@arsh0r , thanks for providing the patch. I generated a pull request for you. This needs to be reviewed properly before merging.

**Comment by fangfufu** [comment]
Fixed via https://github.com/gsliepen/tinc/pull/263#issuecomment-869172119
