### ISSUE TITLE
How does tinc handle "unknown cipher"?

### ISSUE THREAD

**Issue by fangfufu** [gsliepen/tinc#237]
So my Debian machines are all using the follow cipher + digest: 
Cipher = chacha20-poly1305
Digest = blake2b512

However my OpenWRT router does not have chacha20-poly1305 and
blake2b512 in its SSL library, so it uses the following: 
Cipher = aes-128-cbc
Digest = sha512

I am a bit surprised that the router's tinc manages to talk to Debian's
tinc, when I set a cipher suite that the router's SSL library does not
recognise. 

I looked at the log, it triggers this line:
https://github.com/gsliepen/tinc/blob/master/src/protocol_auth.c#L297

I am just wondering, what happens after metakey_h() returns false? Does
tinc simply fall back to a more common cipher? Do the two clients
negotiate what to fallback to?

**Comment by fangfufu** [comment]
Hi @gsliepen , yes, I would still like this to be answered, if you have time. :)

**Comment by gsliepen** [comment]
The meta-connections are always using AES in CFB mode, and are not affected by the Cipher setting. The reason is that early versions of tinc never set the meta-connection cipher and digest correctly, and when I tried to fix this is turned out that the protocol relies on the CFB mode. Not all algorithm and mode combinations are valid, so I left it fixed to AES in CFB mode (it does select AES128/192/256 to match the public/private key's size though). Note that the manual only says that [Cipher](https://tinc-vpn.org/documentation/Host-configuration-variables.html#Host-configuration-variables) applies to UDP traffic.

If UDP traffic can't work because both sides don't support each other's ciphers, then it will fall back to routing packets via meta-connections, so it will still seem to work.

Also, the above only applies to the legacy tinc 1.0 protocol; the new protocol in tinc 1.1 uses Chacha20-Poly1305 using an implementation included in the source code, it doesn't rely on OpenSSL or LibreSSL anymore.

**Comment by ROBERT-MCDOWELL** [comment]
ha ok, so that's why when I upgrade to 1.1 connection is down.
It needs to recreate Certs for all nodes in Chacha20 right?

**Comment by fangfufu** [comment]
Nope, you don't have to regenerate certificates. 

The certificates are only used during the initial key exchange. The cipher you specified are for the normal symmetric encryption operations. Basically, two nodes initially establish shared secret using public key cryptography (which uses the certificates), then it switches to symmetric cryptography using shared secrets (which are randomly generated).

**Comment by gsliepen** [comment]
Just a note: if you upgrade from tinc 1.0 to tinc 1.1, you don't have to generate a new RSA key pair, but you do need to generate an Ed25519 key pair used `tinc generate-ed25519-keys`. If you upgrade two nodes that only know each other's RSA keys, they will use that to exchange their newly created Ed25519 keys and then reconnect using the new protocol automatically.

**Comment by ROBERT-MCDOWELL** [comment]
mmhmm, ok so the issue is elsewhere so. is the node and global 1.0 config can be used for 1.1?
when I run in 1.1, all nodes creat the tap in switch mode but no one can contact each others, even if I disabled the lookup.

**Comment by ROBERT-MCDOWELL** [comment]
will try to regenerate the Ed25519 and see, thanks!

**Comment by ROBERT-MCDOWELL** [comment]
ok I renewed the Ed25519 and after restart the error is more clear now
 Error looking up node76.server.ltd port 655: No address associated with hostname
does 1.1 depend to another DNS source than hosts and local bind on linux?

**Comment by fangfufu** [comment]
@gsliepen is the Ed25519 key absolutely necessary in 1.1? Based on my reading of the manual (https://www.tinc-vpn.org/documentation-1.1/tinc.pdf), I need it when ``ExperimentalProtocol = yes``, which is the default. But if I use the old version of the protocol, I can get away with the RSA key. 

I also do note that I came across this: 
https://www.tinc-vpn.org/documentation-1.1/Simple-Peer_002dto_002dPeer-Security.html
I haven't had a proper look at it yet. (On a side note, yes, I did read the whole printed copy of tinc 1.0 manual from front and back at one point)

**Comment by ROBERT-MCDOWELL** [comment]
@fang dunno, I just follow the recommendation of @gsliepen the author.
@gsliepen
I really don't know what's happening,  I can see nodes connected with netstat but no packet going thru...
I go back to 1.0 for now

**Comment by gsliepen** [comment]
> Error looking up node76.server.ltd port 655: No address associated with hostname
> does 1.1 depend to another DNS source than hosts and local bind on linux?

No, it just uses `getaddrinfo()` that should use whatever the system provides for DNS resolution. If you are chrooting tinc, then be aware that you must have an `/etc/resolv.conf` and resolver libraries inside the chroot environment as well.

**Comment by ROBERT-MCDOWELL** [comment]
ok understood. I actually don't use chroot. r/etc/resolve.conf is the conf of dnsmasq (127.0.01) and real dns server are at /etc/resolv.dnsmasq.
what is the max level of debug  when runnin tincd -d ?

**Comment by fangfufu** [comment]
@ROBERT-MCDOWELL , have a look at this: https://www.tinc-vpn.org/documentation/Debug-levels.html

**Comment by ROBERT-MCDOWELL** [comment]
ok I succeeded to connect 3 nodes on 4 by replacing hosts to ip in Address setting. I really don't know why hostname stopped to work with tinc-1.1 so I gave up.
now my new issue is one node is still not connecting to others, despite of the same config.

**Comment by ROBERT-MCDOWELL** [comment]
all nodes are working now, apparently a file was corrupted...
I kept the Addresses as IP and not hostname.
I'm going to test now.
thanks @gsliepen
