### ISSUE TITLE
tinc reload

### ISSUE THREAD

**Issue by ptorrent** [gsliepen/tinc#243]
Hello !

We have approximately 150 tinc nodes on our network and one "server". All nodes are configured "ConnectTo = server". When we add a new node (we write the file + tinc reload), all connected nodes disconnect and then reconnect.

Is it possible to avoid this?

Thanks for your answer and your work !

**Comment by Nable80** [comment]
Hi!

Did you try sending SIGHUP? You can send it with ``tincd -n netname -k HUP`` , where ``netname`` is a name of your VPN.

From ``man tincd``:
> **SIGNALS**
>     **ALRM**    Forces tincd to try to connect to all uplinks immediately.  Usually tincd attempts to do this itself, but increases the time it waits between the attempts each time it failed, and if tincd didn't succeed to connect to an uplink the first time after it started, it defaults to the maximum time of 15 minutes.
>     **HUP**     Partially rereads configuration files.  Connections to hosts whose host config file are removed are closed.  New outgoing connections specified in tinc.conf will be made.  If the --logfile option is used, this will also close and reopen the log file, useful when log rotation is used.

**Comment by ptorrent** [comment]
Thanks !

I'm using "tinc version 1.1pre14 (built Sep 18 2017 09:05:03, protocol 17.7)" (tincd --version)

When a I try tincd -n netname -k HUP

tincd: invalid option -- 'k'
Try `tincd --help' for more information.

What I'm doing wrong ?

Thanks !

**Comment by Nable80** [comment]
Oh, this option is present in 1.0 branch (that is used by most distros) but it was removed in 1.1 branch. It looks like you can still send this signal manually (``man pkill``) or try to use ``tincctl`` tool (it may be called ``tinc`` in your distro). I've found its description here: https://github.com/gsliepen/tinc/blob/1.1/doc/tinc.8.in

**Comment by ptorrent** [comment]
Thanks ! It's works. Is there a way to do it on windows ? 

tincd.exe -c C:\Users\ptorrent\AppData\Local\app\tinc\client --pidfile=C:\Users\ptorrent\AppData\Local\app\tinc\client\process.pid 

I don't have any process.pid file

**Comment by gsliepen** [comment]
If you are using tinc 1.1pre14, then `tinc.exe -c ... --pidfile=... reload` should do the same as sending the HUP signal. However, if you are just adding a new host config file, you do not need to reload at all, tinc will pick it up automatically as soon as the new peer tries to connect to it.

**Comment by ptorrent** [comment]
Thanks for your answer !

On windows we're using tinc version 1.0.36.

It's a little bit hard for me to understand difference between tinc/tincd.

This is how we start tinc on windows : 
tincd.exe -c C:\Users\ptorrent\AppData\Local\app\tinc\client --pidfile=C:\Users\ptorrent\AppData\Local\app\tinc\client\process.pid

But I don't see any pidfile (C:\Users\ptorrent\AppData\Local\app\tinc\client\process.pid
 doesn't exist).

Is there a way to reaload tinc on Windows with tincd 1.0.36. ?

Thanks a lot for your support !

**Comment by gsliepen** [comment]
There is no way to have tinc reload the config files on Windows with tincd 1.0.36, you would need the 1.1pre version. But again, if you are just adding a host config file, you do not need to reload tinc at all.

**Comment by ptorrent** [comment]
Thanks for your support and all your work !

**Comment by Nable80** [comment]
Do you have any additional questions or it's time to close this issue?

**Comment by ptorrent** [comment]
Everything is ok for me. Thanks again !
