### ISSUE TITLE
Compilation breaks without deprecated OpenSSL APIs

### ISSUE THREAD

**Issue by neheb** [gsliepen/tinc#244]
It seems m4/openssl.mk checks for the existence of OpenSSL_add_all_algorithms, which is a deprecated API.

I currently pass  ac_cv_have_decl_OpenSSL_add_all_algorithms=yes since the actual code is fine. Would be great to fix.

**Comment by fangfufu** [comment]
Does this affect version 1.0 or 1.1?

**Comment by neheb** [comment]
Looks like both.

**Comment by gsliepen** [comment]
Still needs to be fixed for 1.0.

**Comment by gsliepen** [comment]
Fixed for 1.0 in commit c0331713431949a5fd6bf47501b9fadf6489c5c1.
