### ISSUE TITLE
[IDEA][CODE QUALITY] Use Gravity to help clean up code and avoid possible security issues

### ISSUE THREAD

**Issue by unquietwiki** [gsliepen/tinc#246]
I was recently made aware of [Gravity](https://github.com/marcobambini/gravity), which is a lightweight C99 scripting VM to add object-oriented support & modern features. It's MIT-licensed, so it should be GPLv2-compatible, and it would open up further development to folks with experience in newer development environments.

Thoughts?

**Comment by gsliepen** [comment]
I've never heard of Gravity before. Moving to some niche language is not helpful, it will take a lot of time, and almost no developers are familiar with that language. It needs a VM, which makes me think it is more suitable as some embeddable scripting language like Lua than for programs that need to access the system directly like VPNs. If there really is a need to change languages, then I think only  C++ or Rust would be candidates.

**Comment by unquietwiki** [comment]
Hey @gsliepen . I think the point of this is to be able to write newer code & still have it compile as C99; which I've been lead to believe is a requirement for a lot of these projects. Your point on Rust as an alternative is a good one: there's a lot of action there, and it'd offer code safety that'd be ideal for the project.

**Comment by gsliepen** [comment]
Gravity's compiler is itself written in C99, but the output of the Gravity compiler is not C99 code.

**Comment by unquietwiki** [comment]
Ah. Well, in that case, I can close this as something already considered, and folks can chime in on Rust or whatnot. BTW, I've enjoyed using the software over the years, and glad to see it's still around!
