### ISSUE TITLE
How can we help make tinc better ?

### ISSUE THREAD

**Issue by wenerme** [gsliepen/tinc#253]
I really like tinc and use it everywhere, but don't have time to learn the internal and contribute.

Use tinc 1.1pre, but with regular crash and a lot hiccup like 

```
Handshake phase not finished yet from master_1 (192.168.1.2 port 655)
No key from master_1 after 10 seconds, restarting SPTPS
Got REQ_KEY from master_1 while we already started a SPTPS session!
Invalid packet seqno: 0 != 1 from master_1 (192.168.1.2 port 655)
Failed to decrypt and verify packet from master_1 (192.168.1.2 port 655)
```

When this happen, the service will fail and heal after a while.

Is it possible to sponsor or some how to help tinc's dev ?

**Comment by dotcommmm** [comment]
@wenerme We are facing the exact same issue. How did you resolve this issue? Or did you find a workaround?

**Comment by wenerme** [comment]
> @wenerme We are facing the exact same issue. How did you resolve this issue? Or did you find a workaround?

add restart for tinc service

**Comment by dotcommmm** [comment]
> 

Thanks for your reply @wenerme ! Can you please clarify what kind of restart we should do :)? 
If we restart the service, all existing connections will be dropped all the time?

**Comment by wenerme** [comment]
When tinc hiccup, it's ok, but you should avoid the tinc crash, here is my tinc openrc https://github.com/wenerme/wener/blob/master/notes/service/network/vpn/tinc/README.md#tincnetname

```
retry="${TINC_RETRY:-TERM/60/KILL/10}"
```

this will restart tinc when tinc crash, even 1.18 tinc stil crash sometimes. When tinc crashed, all connections already dropped.
