### ISSUE TITLE
tinc-vpn.org can't be reached in china.

### ISSUE THREAD

**Issue by huapox** [gsliepen/tinc#256]
As the title says.  the website can't be reached.

```bash
Administrator@sam-pincun  ~
$ ping tinc-vpn.org

正在 Ping tinc-vpn.org [31.13.75.5] 具有 32 字节的数据:   #just no return
```

**Comment by wenerme** [comment]
That's the problem of China.

**Comment by vimagick** [comment]
@huapox @wenerme 
As you can see, you live inside of the GreatFireWall.

**Comment by fangfufu** [comment]
I don't think this is relevant to this project.
