### ISSUE TITLE
2 same host connected

### ISSUE THREAD

**Issue by ptorrent** [gsliepen/tinc#257]
Hello,

We have an user who has two computers. On each of them he has the same host. Currently if he forgets to close the application on the other computer, tinc enters a subnet up / down loop. In fact both tinc connects / disconnects until it stops the other application.

Is there a way to block new connections if a host is already connected?

**Comment by gsliepen** [comment]
The solution is to have two different host configuration files, each with a unique `Name`. Note that you can still use the same `Subnet`s for the two hosts.

**Comment by ptorrent** [comment]
Thanks for your answer ! What happend is 2 hosts with same subnet are connected at the same time ?

**Comment by gsliepen** [comment]
You can explicitly give each [`Subnet`](https://www.tinc-vpn.org/documentation/Host-configuration-variables.html#index-Subnet) a weight, the host that is online with the lowest weight will be chosen as the destination. If you don't specify weights or if you give them the same weight, it's undocumented what happens (but currently it will use the host with the `Name` that comes first alphabetically).

**Comment by ptorrent** [comment]
@gsliepen are you sure about that ? Here my example.

Node A (windows client) don't have Node B in hosts (tincd is running)

I add Host B (linux client) in hosts directory. B already have Node A in his hosts.

I'm not able to join A from B, and B from A. Making a tincd reload on windows don't work. I have to restart tincd on node A + B to be sure it's work.

A running on 1.1pre15
B running on 1.0.36

Any idea ?

**Comment by fangfufu** [comment]
Closing off answered questions.
