### ISSUE TITLE
How to realize the function of VPN through Tinc.

### ISSUE THREAD

**Issue by Aloneposix** [gsliepen/tinc#262]
Hello

I want to use Tinc VPN to realize the function of OpenVPN. When the local network is connected to a remote server, I can use the server's IP to access external resources. However, after setting up the environment through the tutorial on the network, I cannot access Google through the server's IP. I am a novice, looking forward to your reply

https://www.digitalocean.com/community/tutorials/how-to-install-tinc-and-set-up-a-basic-vpn-on-ubuntu-18-04

**Comment by bqrs01** [comment]
Hi @Aloneposix,

From what I understand, if you want to access traffic through the server's IP, you will need to enable forwarding on the server and also ensure that a default route pointing to the server (in the tinc tunnel) is added on the client.

**Comment by fangfufu** [comment]
Which OpenVPN tutorial are you referring to? 

Tinc only establishes the VPN itself, you need to manually configure things like DHCP and NAT. Please have a look at this: 
https://tldp.org/HOWTO/html_single/Masquerading-Simple-HOWTO/

**Comment by gsliepen** [comment]
This might also be relevant: https://www.tinc-vpn.org/examples/redirect-gateway/

**Comment by fangfufu** [comment]
Closing off answered questions.
