### ISSUE TITLE
high ping inside tunnel and packet loss if traffic via tinc became more than 30 Mbit/s

### ISSUE THREAD

**Issue by sharewax** [gsliepen/tinc#264]
Hello, I've the issue with stability of VPN via tinc if traffic became more than 30 Mbit/s.
Version of tinc is 1.0.35 from epel (Centos 7).
from one side  - VM with 4 CPU. CPU load above 10% during work.
<img width="1250" alt="выява" src="https://user-images.githubusercontent.com/9673243/123230959-6c51e000-d4e0-11eb-9a31-f0366ce812f7.png">
<img width="1212" alt="выява" src="https://user-images.githubusercontent.com/9673243/123231034-7e338300-d4e0-11eb-9c29-9dbda7085e7e.png">

If traffic is a little bit more than 20 Mbit/s - packet loss is observed and latency became more. CPU is not under high load in this time.

What more info do you need from me for investigate this behaviour?
config is
 /etc/tinc/sg2ne1/tinc.conf
```
Name = sg2vopenvpn2
ConnectTo = ne2mgmtvip
Interface = tun0
TCPOnly = yes
# added after reading https://github.com/gsliepen/tinc/issues/195
TunnelServer = yes
ProcessPriority = high
# added 06.03.2020
PingTimeout = 15
ReplayWindow = 128
# changed from fast zlib to fast lzo
Compression = 10
# added 19.11.2020
KeyExpire = 86400
```

**Comment by fangfufu** [comment]
Could you run tinc in debug mode, generate some traffic and post some logs please? 
https://www.tinc-vpn.org/documentation/Solving-problems.html

**Comment by sharewax** [comment]
It should be done for both sides or it's enough for one side?

**Comment by fangfufu** [comment]
One side should be enough for now, if we cannot figure what's going on. We might have to do it for both sides.

**Comment by sharewax** [comment]
checked that in one side 20 mbytes/s, in another direction - 2 mbytes/s. So it depends from direction.

**Comment by fangfufu** [comment]
What are the cipher settings for both side?

**Comment by sharewax** [comment]
Digest = sha256
or it should be something else? Where I can check it?

**Comment by fangfufu** [comment]
You don't have to set it. It defaults to ``aes-256-cbc``

**Comment by sharewax** [comment]
Do you have any suggestions for it?
We need speed, not security (in tunnel usually going ssh traffic or https).

**Comment by fangfufu** [comment]
What are the machines on both side?

**Comment by sharewax** [comment]
another side - hw server with 32 cores, 252 Gb RAM. Should be enough for tinc.

**Comment by fangfufu** [comment]
You haven't described which side to which side is slow, and which side to which side is fast.

**Comment by sharewax** [comment]
So from VM to HW - it's fast (from Singapore to China) - 20-30 mbytes/s. ping increase from 65 ms to 400-800 ms.
from HW to VM - it's slow (from China to Singapore) - 2-3 mbytes/s. ping increase from 65 ms to 400-800 ms and some packet loss (5-15%).
CPU is not under high load in both cases - no even one core 100%.

**Comment by sharewax** [comment]
so any possibility to reduce ping inside tunnel during some load? Checked ICMP for public IP addresses - no any looses.

**Comment by gsliepen** [comment]
I see `TCPOnly = yes` is enabled. This causes tinc to tunnel everything over TCP connections, and when there is congestion, this means a lot of packets will be waiting in the TCP send and/or receive buffers for further processing. This explains the high ping, and if you have TCP connections inside the VPN being tunneled over TCP, then you get interaction between the inner and outer retransmission timers, causing the [TCP over TCP meltdown](http://sites.inka.de/bigred/devel/tcp-tcp.html). I recommend you remove `TCPOnly = yes`; tinc will automatically detect if UDP is possible or not, and will fall back to TCP if necessary, but will use the more efficient UDP tunneling whenever possible.

**Comment by sharewax** [comment]
As I remember the biggest issue that tunnel over UDP works very unstable
between Singapore and China, because big Chinese firewall in deal. I'll
check tomorrow for UDP setting.

**Comment by fangfufu** [comment]
What's the upload bandwidth from China to Singapore without Tinc anyway? 

If you have to use TCP, you can always try to use ``tc`` to throttle the bandwidth, so the ping time doesn't become unbearable: 
https://tldp.org/HOWTO/Adv-Routing-HOWTO/lartc.ratelimit.single.html

**Comment by sharewax** [comment]
tested with iperf:
SG server, CN client:
```
iperf -u -c SG -b50MBits -l128 -i5 -t30 -p 45671

iperf -p 45671 -s -u -i5 -l1024K
------------------------------------------------------------
Server listening on UDP port 45671
Receiving 1048576 byte datagrams
UDP buffer size:  208 KByte (default)
------------------------------------------------------------
[  3] local xxx port 45671 connected with xxx port 17806
[ ID] Interval       Transfer     Bandwidth        Jitter   Lost/Total Datagrams
[  3]  0.0- 5.0 sec  19.5 MBytes  32.7 Mbits/sec   0.025 ms 96454/256071 (38%)
[  3]  5.0-10.0 sec  19.6 MBytes  32.8 Mbits/sec   0.019 ms 95832/255996 (37%)
[  3] 10.0-15.0 sec  19.5 MBytes  32.7 Mbits/sec   0.015 ms 96166/256000 (38%)
[  3] 15.0-20.0 sec  19.8 MBytes  33.2 Mbits/sec   0.018 ms 94030/255999 (37%)
[  3] 20.0-25.0 sec  19.8 MBytes  33.3 Mbits/sec   0.015 ms 93420/256003 (36%)
[  3]  0.0-30.0 sec   118 MBytes  33.0 Mbits/sec   0.013 ms 570136/1536000 (37%)

```


CN server, SG client:
```
iperf -p 45671 -s -u -i5 -l1024K
------------------------------------------------------------
Server listening on UDP port 45671
Receiving 1048576 byte datagrams
UDP buffer size:  208 KByte (default)
------------------------------------------------------------
[  3] local xxx port 45671 connected with yyy port 61776
[ ID] Interval       Transfer     Bandwidth        Jitter   Lost/Total Datagrams
[  3]  0.0- 5.0 sec  31.3 MBytes  52.4 Mbits/sec   0.011 ms    0/256054 (0%)
[  3]  5.0-10.0 sec  31.2 MBytes  52.4 Mbits/sec   0.003 ms    0/256000 (0%)
[  3] 10.0-15.0 sec  31.2 MBytes  52.4 Mbits/sec   0.013 ms   23/255997 (0.009%)
[  3] 15.0-20.0 sec  31.2 MBytes  52.4 Mbits/sec   0.009 ms    0/256000 (0%)
[  3] 20.0-25.0 sec  31.3 MBytes  52.4 Mbits/sec   0.013 ms    0/256001 (0%)
[  3]  0.0-30.0 sec   187 MBytes  52.4 Mbits/sec   0.008 ms   23/1536001 (0.0015%)
```
So it seems that channel has issues, I'll try to contact ISP in this case.

**Comment by sharewax** [comment]
They said that it's possible GFW, so no issues with vpn service itself. Thank you.

**Comment by fangfufu** [comment]
If you really want, you can use ridiculous tool such as https://github.com/xtaci/kcptun to wrap around your tinc tunnel. Kcptun definitely makes everything magically go faster, but you are at the risk of GFW throttling bandwidth based on IP, rather than just protocol / port.

**Comment by sharewax** [comment]
thank you, I'll check.

**Comment by sharewax** [comment]
Tested with different parameters, but it's finished with the same results: started at 3 mbytes/s, than became 1.6 mbytes/s and that's all...
