### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by ROBERT-MCDOWELL** [gsliepen/tinc#265]
FYI, with gcc 11 I get a warning 

tincctl.c: In function ‘ask_and_open.constprop’:
tincctl.c:274:47: warning: ‘.tmp’ directive output may be truncated writing 4 bytes into a region of size between 1 and 4096 [-Wformat-truncation=]
  274 |         snprintf(tmpfile, sizeof(tmpfile), "%s.tmp", filename);
      |                                               ^~~~
tincctl.c:274:9: note: ‘snprintf’ output between 5 and 4100 bytes into a destination of size 4096
  274 |         snprintf(tmpfile, sizeof(tmpfile), "%s.tmp", filename);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC       top.o
  CC       ed25519/ecdsagen.o
  CC       openssl/rsagen.o
  CCLD     tinc

thanks

**Comment by fangfufu** [comment]
Which version is this? If you type in ``git log``, it should give you something like:

    commit 4887f56e565727c6ebd5a8a8911d1aa260f0ce6f (HEAD -> master, tag: release-1.0.36, origin/master, origin/HEAD)
    Author: Guus Sliepen <guus@tinc-vpn.org>
    Date:   Mon Aug 26 12:57:03 2019 +0200
    
        Releasing 1.0.36.

What is the commit hash (the string after the word "commit")?

**Comment by ROBERT-MCDOWELL** [comment]
commit b2fe16d635dded2d6c3096d85672696d0b82dcd1 (HEAD -> 1.1, origin/1.1)
Author: Guus Sliepen <guus@tinc-vpn.org>
Date:   Tue Jun 22 22:36:13 2021 +0200

**Comment by ROBERT-MCDOWELL** [comment]
last git fixed it apparently, nice job!
