### ISSUE TITLE
Incidental bug fix in timers

### ISSUE THREAD

**Issue by splitice** [gsliepen/tinc#272]
This commit https://github.com/X4BNet/tinc/commit/13d617f36dbb9d335687c78a68e2cd367ff546f2 fixes a small bug that can cause increased timer jitter if the timer is due to be executed in less than one second. `tv_usec` must also be compared.

As my epoll branch uses execute now (rather than 1usec from now) to reduce syscalls and branches the code isnt directly transplantable. The condition to fix for 1.1 would be:

`diff->tv_sec < 0 || (diff->tv_sec == 0 && diff->tv_usec < 0)`

Or you could move to a similar model. With `timeout_execute` never returning zero you don't syscall on timers due now (micro optimization).

**Comment by gsliepen** [comment]
This should never happen, [`timersub()`](https://linux.die.net/man/3/timersub) should return a `tv_usecs` between 0 and 999,999 according to the manpage. Does this actually happen on your system?

**Comment by splitice** [comment]
@gsliepen well what about?

https://github.com/gsliepen/tinc/blob/73a45af5c50d58867efc7f1778d7c2f9906f50d9/src/event.c#L304

**Comment by splitice** [comment]
Thinking about this. The current implementation works. It's only after moving to epoll when I moved to a 0us trigger (trigger at the time indicated not +1us) that the logic became incorrect.

Strange way that `timersub` expresses negative numbers, but I guess it makes this case simpler.
