### ISSUE TITLE
Auto reload

### ISSUE THREAD

**Issue by ptorrent** [gsliepen/tinc#274]
Hello there !

Is there a way to auto reload tinc when a new host file is created ?

Is TINC detecting changes on hosts directory ?

Thanks !

**Comment by gsliepen** [comment]
It will accept connections from hosts whose host files have been added automatically, no need to restart. If you are adding a `ConnectTo` option for the new host or have `AutoConnect` enabled in tinc 1.1 (the default), then you might want to signal the tinc daemon to reload the configuration (`tincd -n netname -kHUP` for tinc 1.0, `tinc -netname reload` for tinc 1.1).

**Comment by ptorrent** [comment]
@gsliepen are you sure about that ? Here my example.

Node A (windows client) don't have Node B in hosts (tincd is running)

I add Host B (linux client) in hosts directory. B already have Node A in his hosts.

I'm not able to join A from B, and B from A. Making a tincd reload on windows don't work. I have to restart tincd on node A + B to be sure it's work.

A running on 1.1pre15
B running on 1.0.36

Any idea ?

**Comment by fangfufu** [comment]
@gsliepen , I vaguely remember reading about what you said somewhere else, but I can't seem to find it in the official documentation.

**Comment by gsliepen** [comment]
Ah, on Windows with tinc 1.0.x, you can't reload a running daemon. But still, when it gets a connection from B it should just try to open the new host config file. I would try to enable logging to see what is going on. For the Linux client running 1.1pre15, just do:

```
tinc -n netname start -d5 -D
```

Then it will log what is going on to the terminal you run this command in.

**Comment by fangfufu** [comment]
Closing off answered questions.
