### ISSUE TITLE
Weekly / Nightly build

### ISSUE THREAD

**Issue by fangfufu** [gsliepen/tinc#289]
Since we are doing CI. Why don't we generate a weekly or even nightly build? 
(Tagging you, @hg, since you have been working on CI :slightly_smiling_face: )

**Comment by hg** [comment]
Sure, I also find this useful. Most of the required infrastructure is already there. RPM build configs will have to be ported first (probably ripped out from Fedora packages), and whatever weirdness Windows requires to create installers.

No idea about Macs with their notarization requirements. They already have [this](https://github.com/Homebrew/homebrew-core/blob/2684724e2adda0c0a220481e58b1bb69e42d7a6c/Formula/tinc.rb) and it seems to be the preferred way to install third-party applications, so maybe Mac can be skipped altogether.

I would like to finish the meson port first, though, so as not to repeat the same work twice. (If it's accepted.)

**Comment by fangfufu** [comment]
Done at https://github.com/gsliepen/tinc/commit/7619f84393f824a84e20e03167304b27d3581ac0
