### ISSUE TITLE
It appears that the Github workflows are not running at all.

### ISSUE THREAD

**Issue by fangfufu** [gsliepen/tinc#310]
I created a test commit and a test pull request (https://github.com/gsliepen/tinc/pull/309) to investigate the problem with Windows CI tests. However right now, it appears that Github workflows are not running at all. I don't know if this is intentional. 

@hg @gsliepen

**Comment by fangfufu** [comment]
In the same pull request, I created a commit with dummy files, and it appears to be triggering only the workflows outside of Github.

**Comment by fangfufu** [comment]
I would argue that perhaps https://github.com/gsliepen/tinc/commit/7619f84393f824a84e20e03167304b27d3581ac0 broke the Github workflow.

**Comment by fangfufu** [comment]
This is what's showing up for me: 
![image](https://user-images.githubusercontent.com/2323403/128934513-8560a79f-e11a-4182-94dc-1d4e4508c110.png)

**Comment by gsliepen** [comment]
But it did do https://github.com/gsliepen/tinc/actions/runs/1117726292 and that was for a later commit...

**Comment by fangfufu** [comment]
I made those test commits after you cherrypicked that commit. You can look at my fork's history: 
https://github.com/fangfufu/tinc/commits/windows-CI

We might just have to wait until tomorrow before investigating this further. Github Actions might be down. You can check the status at: https://www.githubstatus.com/

I am attaching a screenshot 
![image](https://user-images.githubusercontent.com/2323403/128936152-ad20dfbf-7418-4f83-88e9-b4a296e34cc7.png)

**Comment by fangfufu** [comment]
> But it did do https://github.com/gsliepen/tinc/actions/runs/1117726292 and that was for a later commit...

Ah! I get what you meant now! The commit I pointed at must have been okay, otherwise the workflows wouldn't run for the later commits. This whole thing might just be Github infrastructure failure... This whole thing reminds me of my day job... :joy:

**Comment by fangfufu** [comment]
The issue was purely due to Github infrastructure failure.
