### ISSUE TITLE
Proxy http

### ISSUE THREAD

**Issue by ptorrent** [gsliepen/tinc#343]
Hi there !

How "Proxy" parameter works ?

![image](https://user-images.githubusercontent.com/6083644/144822250-6a0feed3-34c2-48d5-93c2-4117f83533e0.png)

Does it create a HTTP tunnel ? Is HTTPS supported ?

Thanks for your help !

**Comment by gsliepen** [comment]
Yes, it creates a HTTP tunnel using the [HTTP CONNECT](https://en.wikipedia.org/wiki/HTTP_tunnel#HTTP_CONNECT_method) method. However, it does not support HTTPS. If you want to tunnel over HTTPS, you can use something like [stunnel](https://www.stunnel.org/), or a program that makes a HTTP tunnel over SSL and call it using `Proxy = exec`.

**Comment by ptorrent** [comment]
Thanks for your answer.

When proxy parameter is "http": Is tinc keep trying to connect via default port 655 ?

**Comment by gsliepen** [comment]
When you use `Proxy = http`, you have to add the IP address and port of the proxy to that configuration variable, for example:

```
Proxy = http localhost 8080
```

But if tinc wants to connect via the proxy to another node, it will itself make the connection to `localhost` port `8080`, but then tell the proxy to connect to the other node's address and port. If the other node is listening on port 655, that is what the proxy will connect to on behalf of tinc.

**Comment by ptorrent** [comment]
Thanks !
