### ISSUE TITLE
RTP over TINC

### ISSUE THREAD

**Issue by ptorrent** [gsliepen/tinc#432]
Hello !

Do you know if RTP (SIP) works on TINC VPN ?

**Comment by ROBERT-MCDOWELL** [comment]
Tinc is a protocol agnostic

**Comment by fangfufu** [comment]
If you are talking about this: https://en.wikipedia.org/wiki/Real-time_Transport_Protocol, then yes, it should work. 

> Tinc is a protocol agnostic

That's mostly true, but not strictly true. Tinc can be configured to operate in routing mode (layer 3) or switching mode (layer 2). When it is operating in layer 3, any protocol that needs layer 2 wouldn't work.

**Comment by ptorrent** [comment]
Thanks a lot for your answer. ill try tomorrow in routing mode L3

**Comment by ROBERT-MCDOWELL** [comment]
or set tinc as a TAP.

**Comment by ptorrent** [comment]
Set Tinc as a TAP?

**Comment by ROBERT-MCDOWELL** [comment]
yes, please consult the doc, "man tinc"
